# Get all questions
GET http://127.0.0.1:8000/api/questions/
# GET https://dmoj.ca/api/v2/problems
### (Three hashes separate different requests)

# Get a specific question by ID
GET http://127.0.0.1:8000/api/questions/1/

###

# Create a new question (POST request) this should fail without authentication
POST http://127.0.0.1:8000/api/questions/
Content-Type: application/json

{
    "question_text": "What is life?"
}

### Get new Token 

POST http://127.0.0.1:8000/api/token/
Content-Type: application/json

{
    "username": "ngo",
    "password": "vippro123"
}

### Save the token as a variable
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzMTYzNjEwLCJpYXQiOjE3NDMxNjI4NjksImp0aSI6ImVkOThkYzQ5YmEwMjQ4NzhiMmYyOTcxYWEyZmRkNzM3IiwidXNlcl9pZCI6Mn0.Eb1krd12HRTKJzzCSJ4E_y65p4uq1tODVN2EJ2hsbjs
@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0MzI0OTI2OSwiaWF0IjoxNzQzMTYyODY5LCJqdGkiOiI1ZTNkNDBiY2Y2ZDk0OTQwODE5YzlmMmQ3OTM2MmZjMyIsInVzZXJfaWQiOjJ9.FhCug8Tw9gsF64v6pVaQ_s1yv1GXMn-P6zaq_ELnTdo
### Get Refresh Token
POST http://127.0.0.1:8000/api/token/refresh/
Content-Type: application/json

{
    "refresh": "{{refresh_token}}"
}

###
# Test with token
POST http://127.0.0.1:8000/api/questions/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "question_text": "What is 5+6?"
}

###
# Update a question (PUT request)
PUT http://127.0.0.1:8000/api/questions/1/
Content-Type: application/json

{
    "question_text": "What is 5+6?"
}

###

# Delete a question
DELETE http://127.0.0.1:8000/api/questions/1/