# Generated by Django 5.1.6 on 2025-03-30 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20250322_1744'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': (('edit_own_question', 'Edit own questions'),)},
        ),
        migrations.AddField(
            model_name='question',
            name='authors',
            field=models.ManyToManyField(related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
