# Generated by Django 5.1.6 on 2025-03-30 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_question_options_question_authors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': (('edit_own_question', 'Edit own questions'), ('edit_all_question', 'Edit all questions'), ('edit_public_problem', 'Edit public problems'))},
        ),
        migrations.AddField(
            model_name='question',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
